// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { createWebHashHistory, createMemoryHistory, createWebHistory } from '/Volumes/workspace/front/alibaba/umi-vue/node_modules/.pnpm/@umijs+renderer-vue@4.0.64_vue-router@4.1.6_vue@3.2.45/node_modules/@umijs/renderer-vue';
import type { RouterHistory } from '/Volumes/workspace/front/alibaba/umi-vue/node_modules/.pnpm/@umijs+renderer-vue@4.0.64_vue-router@4.1.6_vue@3.2.45/node_modules/@umijs/renderer-vue';

let history: RouterHistory;
export function createHistory(opts: any) {
  if (opts.type === 'hash') {
    history = createWebHashHistory(opts.basename);
  } else if (opts.type === 'memory') {
    history = createMemoryHistory(opts.basename);
  } else {
    history = createWebHistory(opts.basename);
  }
  return history;
}

export { history };
