// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { inject } from 'vue';
import { AppContextKey } from '/Volumes/workspace/front/alibaba/umi-vue/node_modules/.pnpm/@umijs+renderer-vue@4.0.64_vue-router@4.1.6_vue@3.2.45/node_modules/@umijs/renderer-vue';

export function useAppData() {
  const state = inject(AppContextKey);
  if (!state) {
    throw new Error('AppContext is no provide');
  }

  return state;
}
